name: Build Pure K2P

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.15.2'
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

    - name: Clone source code
      run: |
        cd toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      env:
        TNAME: "K2P-5.0 K2P"
      run: |
        cwd=`pwd`
        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        cd trunk
        sed -i "0,/FIRMWARE_BUILDS_REV.*$/s//FIRMWARE_BUILDS_REV=$(date +%Y%m%d)/" versions.inc
        for m in $TNAME;
        do
          if [ ! -f configs/templates/$m.config ] ; then
            echo "configs/templates/$m.config not found "
            exit 1
          fi
          cp -f configs/templates/$m.config .config
          #####################################################################################
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
          ######################################################################
          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config
          if [ "$m" = "K2P-5.0" ] || [ "$m" = "DIR-878-5.0" ]; then
            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
          else
            echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
          fi
          ####################################################################################
          sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
          echo "Doing clear_tree_simple ..."
          sudo ./clear_tree_simple
          sudo ./build_firmware_modify $m 0
          sudo mv -f images/*.trx /opt/images/$m-3.4.3.9-099.trx
        done
        echo "PackageName=Padavan-K2P-$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: K2P
        path: /opt/images/
